title: Luke Nguyen's Personal Portfolio
logo: /assets/img/PC210029.JPG
description: UCSB Computer Engineering Student Portfolio
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
