title: Luke Nguyen's Personal Portfolio
logo: /assets/img/logo.png
description: UCSB Computer Engineering Student Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
